/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedRoleImport } from './routes/_authenticated/_role'

// Create Virtual Routes

const AuthenticatedTeachersLazyImport = createFileRoute(
  '/_authenticated/teachers',
)()
const AuthenticatedSubjectsLazyImport = createFileRoute(
  '/_authenticated/subjects',
)()
const AuthenticatedStudentsLazyImport = createFileRoute(
  '/_authenticated/students',
)()
const AuthenticatedParentsLazyImport = createFileRoute(
  '/_authenticated/parents',
)()
const AuthenticatedDashboardLazyImport = createFileRoute(
  '/_authenticated/dashboard',
)()
const AuthenticatedRoleClassesLazyImport = createFileRoute(
  '/_authenticated/_role/classes',
)()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedTeachersLazyRoute = AuthenticatedTeachersLazyImport.update({
  path: '/teachers',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/teachers.lazy').then((d) => d.Route),
)

const AuthenticatedSubjectsLazyRoute = AuthenticatedSubjectsLazyImport.update({
  path: '/subjects',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/subjects.lazy').then((d) => d.Route),
)

const AuthenticatedStudentsLazyRoute = AuthenticatedStudentsLazyImport.update({
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/students.lazy').then((d) => d.Route),
)

const AuthenticatedParentsLazyRoute = AuthenticatedParentsLazyImport.update({
  path: '/parents',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/parents.lazy').then((d) => d.Route),
)

const AuthenticatedDashboardLazyRoute = AuthenticatedDashboardLazyImport.update(
  {
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
)

const AuthenticatedRoleRoute = AuthenticatedRoleImport.update({
  id: '/_role',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRoleClassesLazyRoute =
  AuthenticatedRoleClassesLazyImport.update({
    path: '/classes',
    getParentRoute: () => AuthenticatedRoleRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/_role/classes.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_role': {
      id: '/_authenticated/_role'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRoleImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/parents': {
      id: '/_authenticated/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AuthenticatedParentsLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_role/classes': {
      id: '/_authenticated/_role/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedRoleClassesLazyImport
      parentRoute: typeof AuthenticatedRoleImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRoleRouteChildren {
  AuthenticatedRoleClassesLazyRoute: typeof AuthenticatedRoleClassesLazyRoute
}

const AuthenticatedRoleRouteChildren: AuthenticatedRoleRouteChildren = {
  AuthenticatedRoleClassesLazyRoute: AuthenticatedRoleClassesLazyRoute,
}

const AuthenticatedRoleRouteWithChildren =
  AuthenticatedRoleRoute._addFileChildren(AuthenticatedRoleRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedRoleRoute: typeof AuthenticatedRoleRouteWithChildren
  AuthenticatedDashboardLazyRoute: typeof AuthenticatedDashboardLazyRoute
  AuthenticatedParentsLazyRoute: typeof AuthenticatedParentsLazyRoute
  AuthenticatedStudentsLazyRoute: typeof AuthenticatedStudentsLazyRoute
  AuthenticatedSubjectsLazyRoute: typeof AuthenticatedSubjectsLazyRoute
  AuthenticatedTeachersLazyRoute: typeof AuthenticatedTeachersLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRoleRoute: AuthenticatedRoleRouteWithChildren,
  AuthenticatedDashboardLazyRoute: AuthenticatedDashboardLazyRoute,
  AuthenticatedParentsLazyRoute: AuthenticatedParentsLazyRoute,
  AuthenticatedStudentsLazyRoute: AuthenticatedStudentsLazyRoute,
  AuthenticatedSubjectsLazyRoute: AuthenticatedSubjectsLazyRoute,
  AuthenticatedTeachersLazyRoute: AuthenticatedTeachersLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRoleRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/parents': typeof AuthenticatedParentsLazyRoute
  '/students': typeof AuthenticatedStudentsLazyRoute
  '/subjects': typeof AuthenticatedSubjectsLazyRoute
  '/teachers': typeof AuthenticatedTeachersLazyRoute
  '/classes': typeof AuthenticatedRoleClassesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRoleRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/parents': typeof AuthenticatedParentsLazyRoute
  '/students': typeof AuthenticatedStudentsLazyRoute
  '/subjects': typeof AuthenticatedSubjectsLazyRoute
  '/teachers': typeof AuthenticatedTeachersLazyRoute
  '/classes': typeof AuthenticatedRoleClassesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_role': typeof AuthenticatedRoleRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/_authenticated/parents': typeof AuthenticatedParentsLazyRoute
  '/_authenticated/students': typeof AuthenticatedStudentsLazyRoute
  '/_authenticated/subjects': typeof AuthenticatedSubjectsLazyRoute
  '/_authenticated/teachers': typeof AuthenticatedTeachersLazyRoute
  '/_authenticated/_role/classes': typeof AuthenticatedRoleClassesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/parents'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/classes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/parents'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/classes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_role'
    | '/_authenticated/dashboard'
    | '/_authenticated/parents'
    | '/_authenticated/students'
    | '/_authenticated/subjects'
    | '/_authenticated/teachers'
    | '/_authenticated/_role/classes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_role",
        "/_authenticated/dashboard",
        "/_authenticated/parents",
        "/_authenticated/students",
        "/_authenticated/subjects",
        "/_authenticated/teachers"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/_role": {
      "filePath": "_authenticated/_role.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_role/classes"
      ]
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/parents": {
      "filePath": "_authenticated/parents.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/students": {
      "filePath": "_authenticated/students.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/subjects": {
      "filePath": "_authenticated/subjects.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/teachers": {
      "filePath": "_authenticated/teachers.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_role/classes": {
      "filePath": "_authenticated/_role/classes.lazy.tsx",
      "parent": "/_authenticated/_role"
    }
  }
}
ROUTE_MANIFEST_END */
